Add ALT Linux to installation-guide.rst
vala-lang/vala-docs pull request #45
Opened 2024-08-11 20:59 UTC by Rirusha

2024-08-12 03:31 UTC, lw64 commented on source/installation-guide.rst
> +   # apt-get install vala
that seems to be the way not just for ALT linux, but all ubuntu/debian based distros, afaik?

2024-08-12 08:56 UTC, Rirusha commented on source/installation-guide.rst
> +   # apt-get install vala
ALT has roots from Mandrake and is currently a completely independent distribution. The command is the same as where you described. But it is incorrect to put them side by side, since they have nothing in common except the name of the package manager utility.

2024-08-22 22:37 UTC, colinkiama commented on source/installation-guide.rst
> +   # apt-get install vala
There is a specific detail about Debian distribution instructions that may not apply to ALT Linux:

> You need to install *-dev packages, to get development files on Debian.

So it does make sense for ALT Linux to have its own section

2024-08-22 22:40 UTC, colinkiama requested changes
Thank you for making this pull request! Just one more change is needed before this can be merged.

2024-08-23 05:20 UTC, Rirusha commented on source/installation-guide.rst
> +~~~~~~
Fixed 👌

2024-08-23 08:00 UTC, merged